### ISSUE TITLE
Detecting JPEG images using magic numbers

### ISSUE THREAD

**Issue by geirmyk** [lstein/Perl-GD#15]
Hi,

I am creating a new image using GD::Image->new($jpg_file), where $jpg_file is a filename pointing to a file on disk.
The JPEG file on disk is valid. But the function returns undef, as the first four bytes of the JPEG image on disk does not match the pattern in the _image_type function: The fourth byte is \376.
If I create the GD image using newFromJpeg, it works fine.
Do you know if there are any issues related to this?
I see that the magic function detection was changed in v2.42. Unfortunately, I am not aware of the various patterns which can occur as the first four bytes in JPEG files.
By the way, we are using GD::Image for sizing images in various formats.

Kind regards,
Geir Myklebust

**Comment by denisu** [comment]
I recently noticed the same problem, there is a fix from 2007 here: https://rt.cpan.org/Public/Bug/Display.html?id=26146

I am currently overwriting this function in my code until the fix gets applied.

**Comment by rurban** [comment]
This was fixed with 2.57
