### ISSUE TITLE
Build.PL missing custom install prefix

### ISSUE THREAD

**Issue by vanzod** [lstein/Perl-GD#19]
I need to install the GD module in a separate directory other than the default Perl modules one. The problem is that `Build.PL` does not seem to support a custom install prefix from command line and installing with the `Makefile.PL` does not seem to work since no object files are generated.

**Comment by SethosII** [comment]
Same here, see the [referenced issue](https://github.com/hpcugent/easybuild-easyconfigs/issues/4394) for details. In short: the archive distributed via [CPAN](http://search.cpan.org/%7Elds/GD/) has a file without write permissions for anyone, which leads to build errors and when one fixes this there are errors during testing with both the GitHub and CPAN version 2.56 (`Can't locate loadable object for module GD`).

If further infromation is needed, just let us know.

**Comment by rurban** [comment]
2.57 will switch back to EUMM, it works there.

**Comment by rurban** [comment]
There's no Build.PL anymore. Use the EUMM recipes
