### ISSUE TITLE
test cases fail for Windows. libgd missing GIF support

### ISSUE THREAD

**Issue by jameysiddiqui** [lstein/Perl-GD#27]
Hi,

I am trying to execute test cased for GD-2.68. with Libgd and GD module build with VS2013
But the test case fails with below error

**Can't locate object method "newFromGif" via package "GD::Image" at t\transp.t line** 

```
"-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib\lib', 'blib\arch')" t\*.t
t\fork.t .................. skipped: Test::Fork required
t\GD.t .................... 1/13 # Testing gd 2.2.5 using gd2 support.
# ignore corrupt png error messages...
t\GD.t .................... ok
t\HSV.t ................... ok
t\Polyline.t .............. ok
t\transp.t ................ Can't locate object method "newFromGif" via package "GD::Image" at t\transp.t line 13.
t\transp.t ................ 1/12 # Looks like your test exited with 255 just after 1.
t\transp.t ................ Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 11/12 subtests
t\z_kwalitee.t ............ skipped: No RELEASE_TESTING
t\z_manifest.t ............ skipped: requires a git checkout and a unix for git and diff
t\z_pod-spell-mistakes.t .. skipped: No RELEASE_TESTING
t\z_pod.t ................. skipped: No RELEASE_TESTING

Test Summary Report
-------------------
t\transp.t              (Wstat: 65280 Tests: 1 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 12 tests but ran 1.
Files=9, Tests=16,  2 wallclock secs ( 0.06 usr +  0.03 sys =  0.09 CPU)
Result: FAIL
Failed 1/9 test programs. 0/16 subtests failed.
NMAKE : fatal error U1077: 'C:\this_is_a_fake_path\this_is_a_fake_path\this_is_a_fake_path\this_is_a_fake_path\this_is_a_fake_path\this_is_a_fake_path\this_is_a_fake_path\bin\iwperl.exe' : return code '0xff'
Stop.
```
Please let me know any inputs

Thanks,
Jamey

**Comment by jameysiddiqui** [comment]
Thanks for reply
I am using following command build libgd: nmake /f windows\Makefile.vc check
as mentioned in readme through Visual studio Command prompt
It doesn't generates gdlib-config nor pkgconfig/gdlib.pc,It generates only libgd.dll and libgd.lib

Also its mentioned in libgd 2.2.5:
echo "gdlib-config: warning: this script is deprecated;" \"please use the pkg-config file instead." >&2

I am not sure if  gdlib-config will still be generated by libgd
I have not seen any option to disable/enable GIF support in libgd code though there are options 
for other features
CFLAGS= $(CFLAGS) \
       /DWIN32=1\
       /D_WIN32=1\
       /DMSWIN32=1\
       /DBGDWIN32=1\
       /DHAVE_FT2BUILD_H=1\
       /DHAVE_GD_H=1\
       /DHAVE_ICONV_H=1\
       /DHAVE_GD_BUNDLED=1\
       /DHAVE_LIBFREETYPE=1\
       /DHAVE_LIBJPEG=1\
       /DHAVE_LIBPNG=1\
	   /DHAVE_LIBWEBP=1\
       /DHAVE_LIBZ=1\
	   /DHAVE_LIBXPM=1\
       /DHAVE_LIBTIFF=1\
       $(INCLUDES)

I tried building GD 2.68  using the  --options "JPEG,FT,PNG,GIF,XPM,ANIMGIF"
but still it fails.
Please let me know anything wrong I am doing 

Thanks,
Jamey

**Comment by rurban** [comment]
I'm no expert in libgd and i'm a bit busy right now.
Can you please bug libgd why they don't support GIF?

**Comment by jameysiddiqui** [comment]
there is no option to disable/enable GIF from LIBGD, It seems GIF is supported by default.
Discussion:https://github.com/libgd/libgd/issues/417

**Comment by rurban** [comment]
GIF will soon be reenabled by default, since the patent expired.

The problem is that a package without gdlib-config needs to probe libgd like via configure with a m4 recipe which features are enabled. This is a severe regression.
There's not even a m4 for that in autoconf-archive, and the gdlib.pc is useless, as it doesn't contain the DEFINES.

**Comment by rurban** [comment]
I've improved now the feature probes, for both cases.
GIF and GD and all other features should be detected now on perl Makefile.PL
