### ISSUE TITLE
please add support for BMP to GD::Image

### ISSUE THREAD

**Issue by pryrt** [lstein/Perl-GD#48]
libgd has included Windows Bitmap [.bmp support](https://libgd.github.io/manuals/2.3.3/files/gd_bmp-c.html) (`gdImageBmp` and `gdImageCreateFromBmp` and associated) since [libgd 2.1.0-alpha1](https://github.com/libgd/libgd/commit/1a022a579bcbb450d8828d9f2e86205ddabfd40e).

This is _different_ from [WBMP support](https://libgd.github.io/manuals/2.3.3/files/gd_wbmp-c.html) ([WBMP](https://en.wikipedia.org/wiki/Wireless_Application_Protocol_Bitmap_Format "Wireless Application Protocol Bitmap Format") is a monochrome format, whereas Windows [BMP](https://en.wikipedia.org/wiki/BMP_file_format) allows anything from monochrom to full-color images; WMBP format uses gdImageWBMP/gdImageCreateFromWBMP/etc, which you have already implemented with `newFromWBMP` and `->wbmp`).

I have confirmed with GD 2.76 libgd 2.2.5 (strawberry perl v5.32.1) that if I output a GD::Image with `$img->wbmp($fg)`, then no default Microsoft tool (mspaint.exe, Photo Viewer, etc) can read it as a Windows Bitmap (.bmp), because it's not a valid Windows bitmap file.  But if I get a tool (like ImageMagick) that understands the monochrome WBMP format, it reads it just fine.  Similarly, `->newFromWBMP` cannot read a standard Windows .bmp file. 

There is no `GD::Image::newFromBmp()` or `->bmp()` pair for input/output of the Windows Bitmap format (`Undefined subroutine &GD::Image::newFromBmp`).

Since `gdImageBmp` and `gdImageCreateFromBmp` already exist in libgd 2.1 and newer (and are thus present in my libgd 2.2.5 or in the libgd 2.3.3 that you've supported since at least v2.74), it would be really nice if support for that feature of libgd could be added to GD::Image.  (If you don't want to try to auto-identify it for `GD::Image::new()`, that's fine with me.)

But whether or not it gets added, the documentation for `GD::Image->newFromWBMP` should be changed for two things: 
1) Since WBMP is not a Windows BMP, and is not compatible with the windows bitmap format, it shouldn't say it is.
2) Since WBMP is a monochrome format, a truecolor option isn't needed.

Thank you.

**Comment by rurban** [comment]
Done, thanks
